
spring:
  application:
    name: testForMaffile
  profiles:
    active: dev
  config:
    import: optional:nacos:testForMaffile-dev.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml