
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import: optional:nacos:gateway-service-dev.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 121.41.228.22:8848
      config:
        server-addr: 121.41.228.22:8848
        file-extension: yml

