server:
  port: 8081

spring:
  application:
    name: content-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iot_tiktok?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 205501
  jackson:
    default-property-inclusion: non_null # JSON 处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.iot.commonModules.entity # 别名扫描包

# Knife4j 配置 (SpringDoc OpenAPI)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn  # 中文界面

#  redis:
#      port: 6379
#      password: redis102425Abcd@
#      host: 127.0.0.1

logging:
  level:
    com.content: debug