
spring:
  application:
    name: content-service
  profiles:
    active: dev
  config:
    import: optional:nacos:content-service-dev.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 121.41.228.22:8848
      config:
        server-addr: 121.41.228.22:8848
        file-extension: yml


  data:
    redis:
      port: 6379
      host: 114.55.242.24
      password: redis102425Abcd
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iot_tiktok?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 205501

  jackson:
   default-property-inclusion: non_null # JSON 处理时忽略非空字段

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iot.commonModules.entity # 别名扫描包
  configuration:
      # 开启日志打印（会输出完整SQL和参数）
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # 日志级别（可选，配合下面的logging使用）
      log-prefix: mybatis
      map-underscore-to-camel-case: true

# Knife4j 配置 (SpringDoc OpenAPI)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn  # 中文界面



logging:
  level:
    com.iot.content: debug
